{{- if .Values.service.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.common.replicaCount }}
  selector:
    matchLabels:
      {{- include "microservices.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "microservices.selectorLabels" . | nindent 8 }}
      {{- with .Values.common.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.common.serviceAccount.create }}
      serviceAccountName: {{ .Values.common.serviceAccount.name | default (printf "%s-%s" .Release.Name .Chart.Name) }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.common.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.service.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.service.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.service.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.service.resources | nindent 12 }}
          {{- with .Values.service.config.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.service.config.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.common.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.common.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          {{- if eq .type "preferred" }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .weight }}
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "microservices.selectorLabels" . | nindent 20 }}
                topologyKey: kubernetes.io/hostname
          {{- else }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  {{- include "microservices.selectorLabels" . | nindent 16 }}
              topologyKey: kubernetes.io/hostname
          {{- end }}
      {{- end }}
      {{- with .Values.common.topologySpreadConstraints }}
      topologySpreadConstraints:
        - maxSkew: {{ .maxSkew }}
          topologyKey: {{ .topologyKey }}
          whenUnsatisfiable: {{ .whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              {{- include "microservices.selectorLabels" . | nindent 14 }}
      {{- end }}
{{- end }} 