{{- if and .Values.productService (hasKey .Values.productService "enabled") (eq .Values.productService.enabled true) }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-service-hpa
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
    app.kubernetes.io/name: product-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-service
  minReplicas: {{ .Values.common.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.common.horizontalPodAutoscaler.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.common.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.common.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}
{{- end }}
{{- if and .Values.userService (hasKey .Values.userService "enabled") (eq .Values.userService.enabled true) }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
    app.kubernetes.io/name: user-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: {{ .Values.common.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.common.horizontalPodAutoscaler.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.common.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.common.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}
{{- end }} 