{{- if and .Values.productService (hasKey .Values.productService "enabled") (eq .Values.productService.enabled true) }}
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: {{ .Values.productService.service.type }}
  ports:
    - port: {{ .Values.productService.service.port }}
      targetPort: {{ .Values.productService.port }}
      protocol: TCP
  selector:
    app: product-service
{{- end }}
{{- if and .Values.userService (hasKey .Values.userService "enabled") (eq .Values.userService.enabled true) }}
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: {{ .Values.userService.service.type }}
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: {{ .Values.userService.port }}
      protocol: TCP
  selector:
    app: user-service
{{- end }} 