{{- if .Values.common.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.common.serviceAccount.name | default (printf "%s-%s" .Release.Name .Chart.Name) }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
  {{- with .Values.common.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 